version: '3'

networks:
    django_tutorial:
        driver: bridge

volumes:
    mysql-database:
        driver: local


services:
    mysql:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: django_tutorial_db
          MYSQL_USER: dbuser
          MYSQL_PASSWORD: secret
          TZ: 'Asia/Tokyo'
        volumes:
            - mysql-database:/var/lib/mysql
        networks:
            - django_tutorial
    web:
        build: .
        tty: true
        stdin_open: true
        volumes:
          - .:/django_tutorial
        ports:
            - 8000:8000
        depends_on:
            - mysql
        networks:
            - django_tutorial

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080:1080
            - 1025:1025
        networks:
            - django_tutorial
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        ports:
            - 10083:80
        depends_on:
            - mysql
        volumes:
            - /sessions
        networks:
            - django_tutorial
